Update deprecated XR API
Unity-Technologies/PostProcessing pull request #858
Opened 2019-11-15 21:57 UTC by ewblais

Change deprecated XR API usage to internal API to prevent any warnings from showing up when the package is installed. Also prevent the use of the API on 2020.1 as both APIs will be removed.

2019-11-15 21:57 UTC, ewblais commented on PostProcessing/Runtime/Utils/RuntimeUtilities.cs
> +#if UNITY_EDITOR
```suggestion
#if UNITY_EDITOR
```

2019-11-15 21:58 UTC, ewblais commented on PostProcessing/Runtime/Utils/RuntimeUtilities.cs
> +                /// <summary>
```suggestion
        /// <summary>
```

2019-11-15 21:58 UTC, ewblais commented on PostProcessing/Runtime/Utils/RuntimeUtilities.cs
> +                /// Returns <c>true</c> if single-pass stereo rendering is active, <c>false</c> otherwise.
```suggestion
        /// Returns <c>true</c> if single-pass stereo rendering is active, <c>false</c> otherwise.
```

2019-11-15 21:59 UTC, ewblais commented on PostProcessing/Runtime/Utils/RuntimeUtilities.cs
> +                /// </summary>
```suggestion
        /// </summary>
```

2019-11-15 21:59 UTC, ewblais commented on PostProcessing/Runtime/Utils/RuntimeUtilities.cs
> +                /// <remarks>
```suggestion
        /// <remarks>
```

2019-11-15 21:59 UTC, ewblais commented on PostProcessing/Runtime/Utils/RuntimeUtilities.cs
> +                /// This property only works in the editor.
```suggestion
        /// This property only works in the editor.
```

2019-11-15 21:59 UTC, ewblais commented on PostProcessing/Runtime/Utils/RuntimeUtilities.cs
> +                /// </remarks>
```suggestion
        /// </remarks>
```

2019-11-15 22:00 UTC, ewblais commented on PostProcessing/Runtime/Utils/RuntimeUtilities.cs
> +                // TODO: Check for SPSR support at runtime
```suggestion
        // TODO: Check for SPSR support at runtime
```

2019-11-16 00:00 UTC, Chman requested changes
No need to bump the package version to 2.2.3, use 2.2.2 (published version is 2.2.1, when a version is published we bump the version number so we don't forget to do it later and replace the XX-XX date in the changelog by the correct one when we push it to the registry) :)

2019-11-18 18:53 UTC, ewblais commented on package.json
> +    "version": "2.2.3",
```suggestion
    "version": "2.2.2",
```

2019-11-18 19:19 UTC, Chman approved these changes

2019-11-18 19:20 UTC, merged